### ISSUE TITLE
Docker Install

### ISSUE THREAD

**Issue by Nasjoe** [mhartzel/freelcs#3]
Hi !

I try to install your solution within a Docker container with X forwarding.
I don't know witch ram disk use. I can't see any dev/ram disk within my docker container. 
Did you have any idea ?

Many Thanks,
Jonas.

**Comment by mhartzel** [comment]
Sorry, Docker is not supported, I have only tested installation on real hardware. I heard from another user that Docker instances can not access ram disks, but I can not confirm this since I don't have any experience with Docker yet.

FreeLCS uses a ram disk to store the progress report html page. A ram disk is used instead of the hard disk so that the html page can always be served quickly, also when there is heavy disk access when processing multiple audio files simultaneously.

**Comment by Nasjoe** [comment]
Hi. Thanks for the answer.

Docker can access to host ram disk if we run the container with the --privileged option :)
So we can install freelcs with a X forwarding.

It would be very nice to have a Docker Repo for your solution (Dockerfile on docker hub). The principal problem : We can't install without screen or X-server :/ So we can't automate the install :/

**Comment by mhartzel** [comment]
I may take a look at docker when I have some time. There are also other things to consider when using FreeLCS in Docker:

FreeLCS uses samba to share a disk to the network, so network access is needed.

Disk performance (can a Docker instance access a raid disk).

The company I work for installed FreeLCS on a virtual machine. The physical machine has lots of processing power and multiple virtual machines run on this same server. Most of the vm's don't need processor time all the time, so they can happily share the same hardware.

If installing FreeLCS as a Docker instance fails, you could install it in VirtualBox / VMWare etc.

**Comment by mhartzel** [comment]
One more thing :)

I'm not sure if I understood you correctly, but if you want to have multiple identical FreeLCS instances running, then you can install one and clone this installation to other machines / vms. The first install can be done with X forwarding and the cloning doesn't need X, its done with a bash script.

More about it here: http://freelcs.sourceforge.net/FreeLCS_User_Manual.html#Cloning%20a%20FreeLCS%20installation%20to%20another%20machine%20%28without%20a%20display%29

**Comment by Nasjoe** [comment]
Sorry, i'm french, I know I need to practice my English :)
Docker is very convenient to deploy your solution in seconds.
With small file with text (Dockerfile) , you can Deploy everything that is useful in a command line : 
( https://docs.docker.com/engine/reference/builder/ )

The network and the samba share is not a problem, Docker is like another VM solution.

Your script is interesting. It would be possible to envisage a default configuration and automate the complete installation.
I can help you, I know well enough Docker, But I need to know what exactly the system will execute on startup of the machine, or Is a command to launch at startup that launches all the necessary services ?

Thanks !

**Comment by mhartzel** [comment]
Would you be interested in supporting a Docker version of FreeLCS ? I already support two distros and various versions of those. Every time a new supported os version is published I will install FreeLCS on it and run some regression tests. This means processing a fixed set of files and comparing the new results to old ones so that I can be sure files are processed correctly on the new os version.

FreeLCS is started by a startup script which first creates a ram disk and then launches LoudnessCorrection.py and HeartBeat_Checker.py as background tasks.

On init based systems (Ubuntu 12.04, 14.04, debian 7) the startup script is called:

/etc/init.d/loudnesscorrection_init_script

On systemd based systems (Debian 8, Ubuntu 16.04) there are two files that startup FreeLCS. The first one is a service file that defines what service needs to be started up. This file is called:

/etc/systemd/system/freelcs.service

And this file starts the FreeLCS startup script that is called:

/etc/systemd/system/loudnesscorrection_init_script

On init and systemd based systems the user configuration is stored in file:

/etc/LoudnessCorrection_Settings.pickle

And samba configuration in:

/etc/samba/smb.conf

The backup / cloning script I talked about in an earlier message copies these files to the backup dir. The backup / clone has all files that FreeLCS creates in a system. So making a backup of FreeLCS installation gives you all these files and they can be easily studied.

FreeLCS files are also listed here in the documentation:

http://freelcs.sourceforge.net/FreeLCS_User_Manual.html#Files%20that%20FreeLCS%20creates%20in%20your%20system

**Comment by Nasjoe** [comment]
Thank you for details. I'll look at it more closely to that I have a little more time . The Docker container can run on any system. This can be very convenient.

In terms of the host system , which version is preferred ? Ubuntu 14.04 ?

It keeps track quickly.

**Comment by mhartzel** [comment]
I guess Ubuntu 14.04 is a good choice. There are some quite severe problems now on Ubuntu 12.04. 12.04 updates breaks python3, and one needs to manually force installation of a newer python version from an external repository to get the python3 bugs fixed. Ubuntu 14.04 python3 works fine and the release is supported until April 2019.

One important thing to note is that it does matter which version of the os installer you use. Different versions come with different versions of the kernel and graphics drivers (Canonical calls this "Hardware Enablement Stack") and only specific versions are supported to April 2019. The good versions of Ubuntu installers are: 14.04.0, 14.0.1 and 14.0.5. More about it here: https://wiki.ubuntu.com/Kernel/LTSEnablementStack#Kernel.2BAC8-Support.A14.04.x_Ubuntu_Kernel_Support

If you want to minimize work, you could start Docker support from Ubuntu 16.04. I have not yet tested FreeLCS with the 16.04 beta since it is still work in progress. But later in the spring I will test it and let FreeLCS installer run on 16.04, At the moment the installer refuses to run on anything but supported distros (Ubuntu 12.04, 14.04 and Debian 7, 8). This would mean that you could not start the work yet, but only later in the spring. Ubuntu 16.04 is probably supported until April 2021.

If you decide to go forward and start supporting a Docker version of FreeLCS, I will of course help you any way I can and then we need to exchange email addresses also :)

**Comment by maximehyh** [comment]
Hi @mhartzel,

I am using FreeLCS in a Flask application and I am thinking about deploying this app as a Docker container. Are you still planning on making a Docker image of FreeLCS? 
Thanks!

Maxime

**Comment by mhartzel** [comment]
Sorry Maxime, I have no plans to add another supported platform as every
release must be tested in each. Every platform adds a lot of work. I'm also
not keen of the idea of being responsible for the security updates of a
container (samba, ffmpeg, etc) but as I'm not very familiar with containers
this might be a misunderstanding on my part.

And sorry for taking so long to respond to your question :)

Mikael Hartzell
