### ISSUE TITLE
Installer.py fails with "ValueError: could not convert string to float"

### ISSUE THREAD

**Issue by ottok** [mhartzel/freelcs#4]
I was trying to install on Ubuntu 16.04 following the manual. The step where I launch installer.py fails with:

```
~/freelcs$ ./installer.py 
Traceback (most recent call last):
  File "./installer.py", line 5216, in <module>
    os_version_float = float(os_version)
ValueError: could not convert string to float:
```

I am a Python programmer. Please give me some technical hints on how to go forward. I am happy to write a patch to fix this if you guide me on track on what I should do.

**Comment by ottok** [comment]
Earlier versions yield a different output:
```
~/freelcs-3.1$ ./installer.py 
Traceback (most recent call last):
  File "./installer.py", line 5071, in <module>
    root_window = tkinter.Tk()
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1871, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:10.0"


~/freelcs-3.0$ ./installer.py 
Traceback (most recent call last):
  File "./installer.py", line 5071, in <module>
    root_window = tkinter.Tk()
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1871, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:10.0"
```

Turns out I needed to add `X11UseLocalhost no` to the server sshd_config for X forwarding to really work.

Running installer for 3.1 and 3.0 now works (though they complain about Ubuntu version 16.04), but  3.2 still yields same error message.

**Comment by mhartzel** [comment]
Hi fellow Finnish citizen :)

The official ubuntu 16.04 compatible version of FreeLCS is not published
yet. The version currently on github is work in progress and might be
broken in some new ways.

I'm currently running tests on ubuntu 16.04 and fixing code when I find
problems.

As soon as I have code ready that passes my regression tests I will publish
it :)
On 18 May 2016 16:38, "Otto Kekäläinen" <notifications@github.com> wrote:

I was trying to install on Ubuntu 16.04 following the manual. The step
where I launch installer.py fails with:

~/freelcs$ ./installer.py
Traceback (most recent call last):
  File "./installer.py", line 5216, in <module>
    os_version_float = float(os_version)
ValueError: could not convert string to float:

I am a Python programmer. Please give me some technical hints on how to go
forward. I am happy to write a patch to fix this if you guide me on track
on what I should do.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/mhartzel/freelcs/issues/4>

**Comment by ottok** [comment]
As said, I can help you with developing 16.04 compatibility, but you need to give some pointers first so that the research/learning curve goes faster.

What is the main challenge in 16.04 compatibility at the time?

**Comment by mhartzel** [comment]
There were some problems with changed behaviour from external programs
FreeLCS uses, but I have ironed those out now. One problem remains: ubuntu
has changed from avconv to FFmpeg and its recent versions cut out 10 - 40
ms of audio from the beginning of file when converting mp3 files. This
probably is a minor problem and does not seem to affect other formats, but
I will study it a bit more to see if I can work around it.

If you are in a hurry to run FreeLCS on ubuntu 16.04 then you can download
the latest developement version from github (
https://github.com/mhartzel/freelcs). As far as I know this version works
now fine, and the only problem remaining is the one I mention above. The
version on github now passes my own regression tests on ubuntu 16.04 (some
30 GB of test files produces the same results as the latest published
version of FreeLCS). However I have only tested the github version on the
regular ubuntu 16.04 Desktop version, not ubuntu 16.04 Server yet. I expect
the server version of os to function identically to the desktop version.

I'm planning to release a new version of FreeLCS in 2 - 3 weeks time. I
need to go through the documentation  first and update some things.

You can get the github version by:

- installing git
- by running the command: git clone https://github.com/mhartzel/freelcs.git
- cd freelcs
- run the installer

Don't use this version in a company production environmet yet. I believe
there are no bugs, but I might be mistaken and find some later :)
